WIP: upload web viewer to a bucket
rerun-io/rerun pull request #1606
Opened 2023-03-17 10:46 UTC by emilk

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)

2023-03-17 11:56 UTC, jleibs commented on .github/workflows/rust.yml
> +      image: rerunio/ci_docker:0.5
This will need to be bumped to 0.6
https://github.com/rerun-io/rerun/pull/1605

2023-03-17 12:00 UTC, jleibs commented on .github/workflows/rust.yml
> +    name: Check Rust web build (wasm32 + wasm-bindgen)
```suggestion
    name: Upload web build to google cloud (wasm32 + wasm-bindgen)
```

2023-03-17 15:06 UTC, emilk commented on .github/workflows/rust.yml
> +      image: rerunio/ci_docker:0.5
```suggestion
      image: rerunio/ci_docker:0.6
```

2023-03-17 15:19 UTC, emilk commented
It works! <https://storage.googleapis.com/rerun-web-viewer/web_viewer/index.html?url=https://storage.googleapis.com/rerun-example-rrd/test-rrd/fiat.rrd>

2023-03-20 10:04 UTC, Wumpf requested changes
lgtm, but I'll add a manual trigger now, hold on :)
I'm also thinking that this should be either a separate action file or depend on the other jobs to ensure that we're not uploading something that didn't pass testing 🤔

2023-03-20 10:10 UTC, Wumpf approved these changes
done, plz check

2023-03-20 10:22 UTC, nikolausWest commented
Didn't check if this happens yet but we should make sure these are all put under versioned paths

2023-03-20 23:07 UTC, merged