Update tensor.rs to Handle Trailing Unit-Dimensions in Image Tensors
rerun-io/rerun pull request #1916
Opened 2023-04-19 06:37 UTC by tauseefmohammed2

### What

- Previously, tensor.rs only displayed tensors with shapes of [H, W, 1|3|4] as images, this update addresses the issue by modifying the `image_height_width_channels()`, `is_shaped_like_an_image()`, and `is_vector()` methods to ignore trailing unit-dimensions when checking the shape of the tensor

- This change should improve the user experience by allowing a wider range of image tensor shapes to be displayed as images in tensor.rs

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [ ] I've included a screenshot or gif (if applicable)

2023-04-19 08:06 UTC, emilk requested changes

2023-04-19 08:06 UTC, emilk commented on crates/re_log_types/src/component_types/tensor.rs
>      pub fn is_shaped_like_an_image(&self) -> bool {
we can simplify this quite a bit:

```suggestion
    pub fn is_shaped_like_an_image(&self) -> bool {
        self.image_height_width_channels().is_some()
    }
```

2023-04-19 08:06 UTC, emilk commented on crates/re_log_types/src/component_types/tensor.rs
> +        let mut last_dim = shape.last().unwrap().size;
this will panic if `shape` is empty (for "scalar tensors")

2023-04-19 08:06 UTC, emilk commented
Thanks for the PR! It would be great if you added a simple test of this to `examples/python/api_demo/main.py`

2023-05-02 09:59 UTC, Wumpf commented
@tauseefmohammed2 you're still on that? :)

2023-05-09 16:43 UTC, Wumpf commented
Took the task over in https://github.com/rerun-io/rerun/pull/2075

2023-05-09 16:43 UTC, closed without merging