Allow dragging time cursor in plots
rerun-io/rerun pull request #2115
Opened 2023-05-15 13:37 UTC by emilk

### What
![drag-plot-time](https://github.com/rerun-io/rerun/assets/1148717/f18c45cf-bb62-46c6-828f-92c78a00db0e)

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)

PR Build Summary: {{ pr-build-summary }}

2023-05-15 16:49 UTC, teh-cmc approved these changes

2023-05-16 07:09 UTC, Wumpf requested changes
help text needs also updating. merge in main for that since it's handled differently now

2023-05-16 10:51 UTC, Wumpf commented
well it's not click anymore, it's drag I'd argue. But yeah not a big thing

2023-05-16 10:56 UTC, emilk commented
you can right-click or right-drag to move the time cursor; this PR has not changed that

2023-05-17 07:43 UTC, merged