Improve styling of demo header
rerun-io/rerun pull request #3022
Opened 2023-08-17 11:51 UTC by jprochazk

### What

Fixes https://github.com/rerun-io/rerun/issues/2732
Fixes https://github.com/rerun-io/rerun/issues/2856

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/{{ pr.number }}) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/{{ pr.number }})
- [Docs preview](https://rerun.io/preview/{{ "pr:%s"|format(pr.branch)|encode_uri_component }}/docs)
- [Examples preview](https://rerun.io/preview/{{ "pr:%s"|format(pr.branch)|encode_uri_component }}/examples)

2023-08-18 07:04 UTC, emilk approved these changes

2023-08-21 08:13 UTC, martenbjork requested changes
Awesome! Added some tiny comments, but overall this looks great!

2023-08-21 08:13 UTC, martenbjork commented on scripts/ci/demo_assets/static/index.css
> +  /*color: #262626;*/
Remove comment before shipping.

2023-08-21 10:35 UTC, martenbjork approved these changes
![4b3aef55-8d91-445b-b0ac-6dea92d2ff15_text](https://github.com/rerun-io/rerun/assets/875708/f48bc6a4-4415-4df3-b917-0da2b35ea20d)

2023-08-21 12:20 UTC, merged