Use snake_case `code_examples` like every other folder we have
rerun-io/rerun pull request #3596
Opened 2023-10-02 14:42 UTC by emilk

### What
So irritating when the folder and crate name is different _for one single crate_

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/{{ pr.number }}) (if applicable)

- [PR Build Summary](https://build.rerun.io/pr/{{ pr.number }})
- [Docs preview](https://rerun.io/preview/{{ pr.commit }}/docs) 
- [Examples preview](https://rerun.io/preview/{{ pr.commit }}/examples) 
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)

2023-10-02 15:01 UTC, Wumpf requested changes
Breaks doc page right now:

Before: https://www.rerun.io/preview/69900eaacb6d71faf79e49dfeb84cf33ccc1f673/docs/reference/data_types/archetypes/arrows3d
After: https://www.rerun.io/preview/3edfcb332cf8894f45115764548986668f1f62e8/docs/reference/data_types/archetypes/arrows3d

2023-10-02 15:03 UTC, Wumpf commented
maybe this requires a change on `landing`? In that case, maybe this is a bad moment for this refactor

2023-10-02 15:04 UTC, Wumpf commented on CHANGELOG.md
> +- Added docs/code_examples to the directories checked by py-lint and py-format [#2476](https://github.com/rerun-io/rerun/pull/2476)
let's not change the changelog retroactively!

2023-10-05 05:34 UTC, abey79 commented
Worth noting that all docs folders currently use kebab case.

2023-10-05 06:30 UTC, jprochazk commented
> maybe this requires a change on landing?

Yes, it's hardcoded in a bunch of places there: https://github.com/rerun-io/landing/blob/main/src/github.ts#L177

2023-11-16 18:56 UTC, closed without merging