`DataLoader`s 8: docs, guide, etc
rerun-io/rerun pull request #4567
Opened 2023-12-17 11:56 UTC by teh-cmc

TODO

---

Part of a series of PRs to make it possible to load _any_ file from the local filesystem, by any means, on web and native:
- #4516
- #4517 
- #4518 
- #4519 
- #4520 
- #4521 
- TODO
- TODO
- TODO

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Full build: [app.rerun.io](https://app.rerun.io/pr/4516/index.html)
  * Partial build: [app.rerun.io](https://app.rerun.io/pr/4516/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json) - Useful for quick testing when changes do not affect examples in any way
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4516)
- [Docs preview](https://rerun.io/preview/6ed7787d3cad9b86fb68a48c0e333c8ca20289d8/docs) 
- [Examples preview](https://rerun.io/preview/6ed7787d3cad9b86fb68a48c0e333c8ca20289d8/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

2023-12-18 10:17 UTC, nikolausWest requested changes
Good in general but I think we need to be a bit more explicit about how the binary plugin system works

2023-12-18 10:17 UTC, nikolausWest commented on docs/content/getting-started/opening-any-file.md
> +Rerun ships with a bunch of builtin implementations for that trait, which handle the following filetypes:
```suggestion
The following file types have built-in support in the Rerun Viewer:
```

2023-12-18 10:17 UTC, nikolausWest commented on docs/content/getting-started/opening-any-file.md
> +If the builtin `DataLoader`s don't cover your needs, we expose two ways of implementing and registering your own loaders.
```suggestion
Internally, the [`DataLoader`](https://github.com/rerun-io/rerun/blob/main/crates/re_data_source/src/data_loader/mod.rs) trait takes care of loading files in the viewer.

If the builtin `DataLoader`s don't cover your needs, we expose two ways of implementing and registering your own loaders.
```

2023-12-18 10:17 UTC, nikolausWest commented on docs/content/getting-started/opening-any-file.md
> +
I didn't really follow this section. How does Rerun know what binary to call for a given file? That needs to be explicitly spelled out in this section. I also think there should be a short page under _Reference_ that explains the binary registration + the viewer -> binary protocol (even if it's very simple). I don't believe our users are used to looking in the examples' comments for a description of a communication protocol

2023-12-22 11:26 UTC, nikolausWest approved these changes
Nice! (just a couple small suggestions)

2023-12-22 11:26 UTC, nikolausWest commented on docs/content/howto/open-any-file.md
> +The easiest way to create your own `DataLoader` is by implementing what we call an "external loader": an executable -- written in any language that the Rerun SDK ships for -- that is available on you
```suggestion
The easiest way to create your own `DataLoader` is by implementing what we call an "external loader": a stand alone executable written in any language that the Rerun SDK ships for. Any executable on your `$PATH` with a name that starts with `rerun_loader` will be treated as a `DataLoader`.
```

2023-12-22 11:26 UTC, nikolausWest commented on docs/content/howto/open-any-file.md
> +This executable is just a vanilla Rerun logger.
```suggestion
This executable takes a file path as input on `stdin` and outputs Rerun logs on `stdout`.
```

2023-12-22 11:28 UTC, teh-cmc commented on docs/content/howto/open-any-file.md
> +The easiest way to create your own `DataLoader` is by implementing what we call an "external loader": an executable -- written in any language that the Rerun SDK ships for -- that is available on you
Oof yeah how did I forget that part

2023-12-22 17:05 UTC, merged