Rename `code-examples/roundtrips.py` to `compare_code_example_output.py`
rerun-io/rerun pull request #4775
Opened 2024-01-10 15:12 UTC by emilk

### What
`roundtrips.py` made little sense, since it didn't roundtrip anything. It also name-clashed with another similar script.

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/{{pr.number}}/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/{{pr.number}}/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/{{pr.number}}/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/{{ pr.number }})
- [Docs preview](https://rerun.io/preview/{{ pr.commit }}/docs) 
- [Examples preview](https://rerun.io/preview/{{ pr.commit }}/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

2024-01-10 15:12 UTC, emilk commented
If you haver an even better name suggestion, I'm all ears

2024-01-10 15:38 UTC, Wumpf requested changes

2024-01-10 15:38 UTC, Wumpf commented on docs/code-examples/README.md
> +To run the roundtrip tests, check out `./docs/code-example/compare_code_example_output.py --help`.
this file talks here and above still about roundtrips

2024-01-11 09:21 UTC, Wumpf approved these changes

2024-01-11 10:53 UTC, merged