Configurable dynamic plot aggregation based on zoom-level
rerun-io/rerun pull request #4865
Opened 2024-01-18 16:14 UTC by teh-cmc

Make it so users can configure an aggregation strategy in the rare case where they either have so much data or are so zoomed out that most of their plot results in an overdraw blurb.

Because this builds on top of the range cache, the data is neatly laid out in a memory slice already so this is very cheap to compute.

- Fixes #4271 
- DNR: requires #4856 

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [ ] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/{{pr.number}}/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/{{pr.number}}/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/{{pr.number}}/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/{{ pr.number }})
- [Docs preview](https://rerun.io/preview/{{ pr.commit }}/docs) 
- [Examples preview](https://rerun.io/preview/{{ pr.commit }}/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

2024-01-18 16:20 UTC, teh-cmc commented on crates/re_space_view_time_series/src/visualizer_system.rs
> +                        acc_max.attrs.radius = f32::max(acc_min.attrs.radius, point.attrs.radius);
plain wrong

2024-01-18 16:20 UTC, teh-cmc commented on crates/re_space_view_time_series/src/visualizer_system.rs
> +                        acc_max.attrs.radius = f32::max(acc_min.attrs.radius, point.attrs.radius);
plain wrong

2024-01-18 16:20 UTC, teh-cmc commented on crates/re_space_view_time_series/src/space_view_class.rs
> +}
Honestly I think that's fine but if anyone has a nicer idea on how to setup that can of feedback loop back to the visualizer system :man_shrugging:

2024-01-22 12:50 UTC, nikolausWest commented
I couldn't really spot the differences in the video. Btw, what does MinMax actually do? I would have assumed it output two values, a min and a max.

2024-01-22 12:51 UTC, nikolausWest commented
As we present this option to users (both in the SDK and in the UI) I think it's important we clarify that this is about aggregating when we have multiple points per pixel in the plot

2024-01-23 08:14 UTC, teh-cmc commented
> I couldn't really spot the differences in the video. Btw, what does MinMax actually do? I would have assumed it output two values, a min and a max.

It's exactly what it does, and that results in a line that goes straight up between those two points, since they both live in the same "pixel column".
The result is effectively indistinguishable from what the non-aggregated path would do, except we get there without any overdraw.

2024-01-23 08:17 UTC, teh-cmc commented
> As we present this option to users (both in the SDK and in the UI) I think it's important we clarify that this is about aggregating when we have multiple points per pixel in the plot

This is what the hover says at the moment:
![image](https://github.com/rerun-io/rerun/assets/2910679/e8b88f0f-46d0-47f2-98c9-8f6395966ac7)

2024-01-23 11:28 UTC, emilk requested changes

2024-01-24 08:21 UTC, emilk commented on crates/re_space_view_time_series/src/visualizer_system.rs
> +                        acc_max.attrs.radius = f32::max(acc_max.attrs.radius, point.attrs.radius);
…oh, but `egui_plot::Line` is fixed-width, so maybe not

2024-01-24 10:40 UTC, nikolausWest commented on crates/re_space_view_time_series/src/visualizer_system.rs
> +                        acc_max.attrs.radius = f32::max(acc_max.attrs.radius, point.attrs.radius);
I think the implemented solution for MInMax is surprisingly good. You basically don't notice the difference to no aggregation other than that it's faster.

There are more advanced visualizations that could be nicer (like showing the span) but that feels out of scope for this

2024-01-25 15:23 UTC, nikolausWest commented
This is pretty sweet!

2024-01-25 16:40 UTC, emilk approved these changes
Awesome ⭐

2024-01-25 16:40 UTC, emilk commented on crates/re_space_view_time_series/src/lib.rs
> +    egui::Id::new(format!("plot_{space_view_id}"))
faster, less hacky

```suggestion
    egui::Id::new(("plot", space_view_id))
```

2024-01-25 16:53 UTC, teh-cmc commented on crates/re_space_view_time_series/src/visualizer_system.rs
> +    // We cannot aggregate two points that doesn't live in the same aggregation window to start with.
`don't`

2024-01-25 17:55 UTC, merged