SDK `DataLoader`s 3: barebones C and C++ support
rerun-io/rerun pull request #5330
Opened 2024-02-28 11:38 UTC by teh-cmc

TODO

---

Part of series of PR to expose configurable `DataLoader`s to our SDKs:
- TODO
- TODO
- TODO

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using newly built examples: [app.rerun.io](https://app.rerun.io/pr/5327/index.html)
  * Using examples from latest `main` build: [app.rerun.io](https://app.rerun.io/pr/5327/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [app.rerun.io](https://app.rerun.io/pr/5327/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/5327)
- [Docs preview](https://rerun.io/preview/64395245a524dcf478f714ae4124e9b2aff23148/docs) 
- [Examples preview](https://rerun.io/preview/64395245a524dcf478f714ae4124e9b2aff23148/examples) 
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

2024-02-28 17:23 UTC, Wumpf reviewed
haven't looked through the entire pr yet but to pre-empt the question: using `std::string_view` to pass around non-string bytes is super confusing and strange, let's not do that. I wish the obvious next thing to say was "just use array view" but that's `std::span` and it's C++20. So `std::byte* data, size_t data_size` is the way to go I fear..

2024-02-29 14:02 UTC, Wumpf requested changes
feeling fairly strongly about the api for raw bytes not using a string_view, otherwise (minus typos) lgtm

2024-02-29 14:02 UTC, Wumpf commented on rerun_cpp/src/rerun/recording_stream.cpp
> +        std::string_view filepath, std::string_view contents
as mentioned already, I find `std::string_view` for raw bytes to be extremly confusing. In C++17 the only clear way to pass an array of bytes I'm aware of is `std::byte* data, size_t data_size` :(

2024-02-29 14:39 UTC, teh-cmc commented on crates/rerun_c/src/ptr.rs
> +// ---
:no_mouth:

2024-02-29 15:13 UTC, Wumpf approved these changes

2024-02-29 15:36 UTC, merged