Switch default plot aggregator from `MinMax` to `MinMaxAverage`
rerun-io/rerun pull request #6079
Opened 2024-04-23 07:47 UTC by emilk

This will produce a less jagged plot

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [ ] I've included a screenshot or gif (if applicable)
* [ ] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/{{pr.number}}?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/{{pr.number}}?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/{{pr.number}})
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

2024-04-23 08:37 UTC, Wumpf requested changes
https://github.com/rerun-io/rerun/pull/4987#discussion_r1473951932

> I think this can be quite misleading. If you have a plot that oscillates rapidly between 0-1 and you zoom out, then MinMax will produce a thick plot that fills the 0-1 range (which is very informative), but MinMaxAverage will show a thin plot that sits in 0.5 (very misleading!)

not my words 😄

2024-04-23 08:49 UTC, emilk commented
Yeah, I've changed my mind.

"Misleading when zoomed out" seems to be the default in the industry.
I'd rather have the width change to span min-max (https://github.com/rerun-io/rerun/issues/4969) but that's a lot more work.

We've had customers complain out the jagged plots.

2024-04-23 08:52 UTC, Wumpf commented
well alternatively we could just aggregate less, that should in the limit have the same result

2024-04-23 08:53 UTC, Wumpf commented
that's also what was proposed as the solution back then - if we have a sample per half-pixel then we should be fine

2024-04-24 06:30 UTC, emilk commented
I've changed my mind again. Looking at how awful the plot aggregator in PostHog is I am now convinced that I rather have jagged, ugly plots, than misleading ones.

2024-04-24 06:30 UTC, closed without merging