Document how to run Python examples
rerun-io/rerun pull request #6218
Opened 2024-05-03 15:06 UTC by emilk

There was documentation there, but I couldn't understand it. Thankfully Jeremy told me the magic incantation, so I decided to write it down later.

I decided to remove the `-e examples` part of it, since everything seems to work without it and because this is the docs for the `examples` environment says it is WIP:

https://github.com/rerun-io/rerun/blob/0ac38a4df54c45f2c34f6a75c6044f9785719615/pixi.toml#L39-L40

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/{{pr.number}}?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/{{pr.number}}?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/{{pr.number}})
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

2024-05-03 15:22 UTC, abey79 requested changes
Although that might work, I'm not convinced it's simpler, and it's certainly not how it was intended.

2024-05-03 15:22 UTC, abey79 commented on examples/python/README.md
> +minimal
well that's not really the intended way. All examples are already installed in the `examples` environment, which just needs to have a compatible rerun-sdk there, so:

```
pixi run -e examples py-build
pixi run -e examples minimal
```

2024-05-03 15:22 UTC, abey79 commented on examples/python/README.md
> +minimal
Likewise.

```
pixi run -e examples pip install rerun-sdk==0.15.1
pixi run -e examples minimal
```

2024-05-06 05:34 UTC, emilk commented
It seems like @abey79 convinced @jleibs that `pixi shell` is not the best recommendation, and that the summary should be

```
pixi run -e examples py-build
pixi run -e examples minimal
```

2024-05-06 06:52 UTC, abey79 commented
> It seems like @abey79 convinced @jleibs that `pixi shell` is not the best recommendation, and that the summary should be
> 
> ```
> pixi run -e examples py-build
> pixi run -e examples minimal
> ```

To clarify, `pixi shell` is fine. What I find inappropriate is to advertise using pixi's `default` environment as a recipient to install random stuff, including examples. Our `pixi.toml` declares an `examples` environment that is made for that, and offers isolation from the other pixi environments.

So both are perfectly fine imo:
```
pixi run -e examples py-build
pixi run -e examples minimal
```
and:
```
pixi shell -e examples
pixi run py-build
pixi run minimal
```

The latter case works because `pixi run` recognises that one of its environment has been activated and uses it instead of `default`.

2024-05-31 06:17 UTC, emilk commented
Closed by https://github.com/rerun-io/rerun/pull/6466#pullrequestreview-2089971006

2024-05-31 06:17 UTC, closed without merging