Allow hiding top panel via blueprint
rerun-io/rerun pull request #6409
Opened 2024-05-22 17:32 UTC by jprochazk

### What

- `rrb.TopPanel` is now exposed, works similarly to `rrb.TimePanel`
- `TimePanel` hidden state now fully hides the time panel

### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/{{pr.number}}?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/{{pr.number}}?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [x] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!

- [PR Build Summary](https://build.rerun.io/pr/{{pr.number}})
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

2024-05-22 19:27 UTC, Wumpf requested changes
doesn't actually work ;)

Bunch of things we need to do:
* process the incoming `TopPanel`
* extend docs:
    * what does collapsed vs hidden mean on each of the panels
    * what does collapse_all thingy bool actually do now
    * ... stuff? 


How I tested:
`pixi run python ./docs/snippets/all/views/spatial2d.py`
`pixi run ipython`
then
```py
import rerun.blueprint as rrb
rrb.Blueprint(rrb.TopPanel(state="collapsed")).connect("rerun_example_spatial_2d")
```

2024-05-23 12:52 UTC, jprochazk commented on crates/re_viewer/src/app.rs
> +                if app_blueprint.top_panel_state == PanelState::Expanded {
this is to align with behavior in https://github.com/rerun-io/rerun/pull/6419

2024-05-27 09:32 UTC, Wumpf requested changes
On native mac the hidden top panel doesn't work out, I think we have to do a per-platform thing here

when selected:
<img width="1347" alt="image" src="https://github.com/rerun-io/rerun/assets/1220815/3685b9bc-5e16-4e28-9688-d01216bddaa2">

when unselected:
<img width="1352" alt="image" src="https://github.com/rerun-io/rerun/assets/1220815/4afe0745-7be8-4eca-ae4d-673606db6dcf">

I figure on Windows and Linux this is fine because we don't mange the close buttons there. Also, for web this is obviously a good feature to have (maybe worth noting as well :)).
I'd propose to disable this on Mac (needs to be documented) and makes sure this looks alright on Windows & Linux.

2024-05-27 09:32 UTC, Wumpf commented on rerun_py/rerun_sdk/rerun/blueprint/api.py
> +            Collapsed and hidden both fully hide the top panel.
```suggestion
            Collapsed and hidden both fully hide the top panel.
```
```suggestion
            Collapsed and hidden both fully hide the blueprint panel.
```

2024-05-27 09:32 UTC, Wumpf commented on rerun_py/rerun_sdk/rerun/blueprint/api.py
> +            Collapsed and hidden both fully hide the top panel.
```suggestion
            Collapsed and hidden both fully hide the top panel.
```
```suggestion
            Collapsed and hidden both fully hide the selection panel.
```

2024-05-27 10:22 UTC, jprochazk commented
> I'd propose to disable this on Mac (needs to be documented) and makes sure this looks alright on Windows & Linux.

Instead of disabling it, I made the top panel toggle hide its content instead of the full thing on mac. Currently making sure it looks alright everywhere

2024-05-27 11:11 UTC, Wumpf commented
good idea! Confirmed on my side this looks alright on Mac

2024-05-27 11:12 UTC, Wumpf approved these changes
At first I thought "fully hides the panel" isn't quite right on Mac now, but arguably it still is as we only have the bare minimum title bar that the OS needs essentially (we could shrink it a bit down with only having the mac buttons in there but whatever, can do that later if we _really_ want to optimize this), so let's keep things simple!

Great stuff and thanks for all the followups!

2024-05-27 11:14 UTC, merged