Fix: When launched with a file path, the viewer doesn't listen to any TCP ports
rerun-io/rerun pull request #6951
Opened 2024-07-20 19:45 UTC by petertheprocess

### What

When lauched with files `rerun xxx.rrd`, the viewr doesn't listen to any port.
I am using `rerun-cli 0.17.0 [rustc 1.76.0 (07dca489a 2024-02-04), LLVM 17.0.6] x86_64-unknown-linux-gnu release-0.17.0 d65ca50, built 2024-07-08T13:47:55Z`.

Before this PR:
No log msg shows we are hosting a SDK sever over some ports.
```bash
> rerun /media/Q/eulerBackUp/Box/Box/rerun_samples.rrd
[2024-07-20T19:37:04Z INFO  re_data_loader::load_file] Loading "/media/Q/eulerBackUp/Box/
Box/rerun_samples.rrd"…
[2024-07-20T19:37:04Z INFO  winit::platform_impl::platform::x11::window] Guessed window s
cale factor: 1
[2024-07-20T19:37:04Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_EXT_
swapchain_colorspace
[2024-07-20T19:37:04Z INFO  egui_wgpu] There were 2 available wgpu adapters: {backend: Vu

> rerun
[2024-07-20T19:38:40Z INFO  re_sdk_comms::server] Hosting a SDK server over TCP at 0.0.0.0:9876. Connect with the Rerun logging SDK.
[2024-07-20T19:38:40Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
[2024-07-20T19:38:40Z WARN  wgpu_hal::vulkan::instance] Unable to find extension: VK_EXT_swapchain_colorspace
```
After this PR:
```bash
> target/debug/rerun /media/Q/eulerBackUp/Box/Box/rerun_samples.
[2024-07-20T19:43:09Z INFO  re_data_loader::load_file] Loading "/media/Q/eulerBackUp/Box/
Box/rerun_samples.rrd"…
[2024-07-20T19:43:09Z INFO  re_sdk_comms::server] Hosting a SDK server over TCP at 0.0.0.
0:9876. Connect with the Rerun logging SDK.
[2024-07-20T19:43:09Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
```
### Checklist
* [x] I have read and agree to [Contributor Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [ ] I've included a screenshot or gif (if applicable)
* [ ] I have tested the web demo (if applicable):
  * Using examples from latest `main` build: [rerun.io/viewer](https://rerun.io/viewer/pr/{{pr.number}}?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
  * Using full set of examples from `nightly` build: [rerun.io/viewer](https://rerun.io/viewer/pr/{{pr.number}}?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their usefulness for the next release's CHANGELOG
* [ ] If applicable, add a new check to the [release checklist](https://github.com/rerun-io/rerun/blob/main/tests/python/release_checklist)!
* [ ] If have noted any breaking changes to the log API in `CHANGELOG.md` and the migration guide

- [PR Build Summary](https://build.rerun.io/pr/{{pr.number}})
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)

To run all checks from `main`, comment on the PR with `@rerun-bot full-check`.

2024-07-22 07:30 UTC, Wumpf approved these changes
Thanks for fixing this! Don't see any reason why we wouldn't listen on tcp after loading a file either.

2024-07-22 07:30 UTC, Wumpf commented
python wheel build is a known failure. waiting for rust lint ci to finish, then merge

2024-07-22 07:45 UTC, teh-cmc requested changes
This will break the ability to open multiple files in parallel.

Today, you can do e.g. this:
```
$ rerun file1.rrd  # in terminal 1
$ rerun file2.rrd  # in terminal 2
```
This will open two Rerun windows, one for each terminal.

This works fine because these two windows don't bind to any port, and so they cannot conflict with one another.

With this PR, this would now fail:
```
$ rerun file1.rrd  # in terminal 1
$ rerun file2.rrd  # in terminal 2 -- ERROR: port 9876 taken
```
You'd have to do this instead, which is really weird from a UX standpoint:
```
$ rerun file1.rrd              # in terminal 1
$ rerun file2.rrd --port 9877  # in terminal 2
```

Automatically switching the second viewer to another port that's available isn't really a solution either: it's very impractical to have a bunch of Rerun Viewers open on different random ports.

I believe the correct solution is for `rerun file.rrd` to redirect the data to the already listening viewer for that port, if there is one.
To force-open a new viewer, the user can use `--port XXXX`.

Related:
- https://github.com/rerun-io/rerun/issues/2044

2024-07-22 07:57 UTC, teh-cmc commented
(Added details)

2024-07-22 08:09 UTC, petertheprocess commented
> I believe the correct solution is for `rerun file.rrd` to redirect the data to the already listening viewer for that port, if there is one.
> To force-open a new viewer, the user can use `--port XXXX` as before (and if that port is also already taken, then the forwarding logic applies once again).

This make sense, I can work on it. But I can't do that till Thursdy.

2024-07-23 21:15 UTC, petertheprocess commented
I found that currentlly rerun_sdk handle multiple spawn by simplly assuming the port is running a Rerun Viewer.
[2024-07-23T21:11:25Z INFO  re_sdk::spawn] A process is already listening at this address. Assuming it's a Rerun Viewer. addr=0.0.0.0:9876

2024-07-24 06:53 UTC, teh-cmc commented
Yes, for now you should just assume that if a port is taken, Rerun is what's bound to it.

In the future we will need to make this more robust, see:
- https://github.com/rerun-io/rerun/issues/4019

(:warning: make sure to make a new message if you want to ask us a question -- if you do an edit, we do _not_ a notification, even if you tag us! :scream:)

2024-09-09 06:18 UTC, petertheprocess commented
@Wumpf @teh-cmc

2024-09-09 12:56 UTC, Wumpf commented
>  But I think the best default behavior should be streamming to the active record so that we can megre 2 .rrd file or append new log to a existing one. Any idea?

Sure that would be a nice variant, but that's not what passing files in does today either. E.g. when passing in two images to rerun cli, it creates two application ids one for each image.
Which essentially means that there's two recording streams. There's no real concept of querying a `RecordingStream` since a recording stream is just a utility to send data to a server. If you'd really want to stream to the same recording, you'd use the same application id and recording id and things would merge upon arrival at the server. But again, I don't think that's what we want here anyways.

2024-10-23 09:18 UTC, teh-cmc approved these changes
I like it! Thanks

2024-10-23 09:26 UTC, merged