Emilk/arrow port viewer
rerun-io/rerun pull request #8539
Opened 2024-12-19 09:57 UTC by emilk

### Related
* Waiting on https://github.com/rerun-io/rerun/pull/8534

### What
Port most of our viewer-facing code to arrow1

2024-12-19 11:00 UTC, emilk commented
@rerun-bot full-check

2024-12-19 13:23 UTC, emilk commented
DRAFT: I broke the dataframe view

2025-01-06 10:39 UTC, emilk commented on rerun_py/src/dataframe.rs
> +        #![allow(clippy::unnecessary_wraps)] // In case of feature != "remote"
Unrelated thing I discovered when running `cargo clippy` (without `--all-features`)

2025-01-06 10:39 UTC, emilk commented
@rerun-bot full-check

2025-01-06 13:32 UTC, teh-cmc requested changes

2025-01-06 13:32 UTC, teh-cmc commented on crates/viewer/re_view_dataframe/src/display_record_batch.rs
>      #[allow(clippy::borrowed_box)] // https://github.com/rust-lang/rust-clippy/issues/11940
Not needed anymore I guess?

2025-01-06 13:32 UTC, teh-cmc commented on crates/viewer/re_view_dataframe/src/display_record_batch.rs
> +                .expect("Nanonseconds should be represented as i64");
Both of these statements risk crashing the entire viewer even in release. As unlikely as it is, it's still not worth losing user data over.
It should only crash in debug, and either return a zeroed array or empty array or `None` or an error in release.

2025-01-06 14:17 UTC, emilk commented on crates/viewer/re_view_dataframe/src/display_record_batch.rs
> +                .expect("Nanonseconds should be represented as i64");
Good catch

2025-01-06 14:57 UTC, merged